### PR TITLE
Update include.postload.js

### PR DESCRIPTION
**Pull request by nonmanifold**
this is just a note on bug

### CODE REVIEW

**Comment by snoack** [comment]
This shouldn't be necessary. Can you please provide details how to reproduce that bug?

**Comment by nonmanifold** [comment]
be on page that uses jQuery File Download and begin file download from JS. 
Use a demo page of that plugin: http://jqueryfiledownload.apphb.com/ 
and click "Submit" button on that page.

**Comment by snoack** [comment]
It seems that Chrome doesn't run document_start, but document_end scripts after submitting a form in an iframe generated with JavaScript. Please report that issue at http://crbug.com

**Comment by snoack** [comment]
Duplicate of #7. Also see [issue 1370](https://issues.adblockplus.org/ticket/1370) and [Chrome bug 416907](https://crbug.com/416907).

**Pull request closed without merging**
